name: Publish Nugets

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
  
    env:
        BUILD_CONFIG: 'Release'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Bump versions
      uses: SiqiLu/dotnet-bump-version@2.0.0
      with:
        version_files: "**/*.csproj"
        version_mask: 0.0.1.0
        version_overwrite: "*.*.*.0-alpha"
        github_token: ${{ secrets.GITHUB_TOKEN }}
   
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore 

    - name: Pack API Project
      run: dotnet pack VpnHood.AccessServer.Api --configuration $BUILD_CONFIG -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg 
          
    - name: Pack Abstractions Project
      run: dotnet pack VpnHood.AccessServer.Abstractions --configuration $BUILD_CONFIG -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg 

    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
